colors:
  primary:
    foreground: '0xABB2BF'
    background: '0x1E2127'

  normal:
    black:      '0x1E2127'
    red:        '0xE06C75'
    green:      '0x98C379'
    yellow:     '0xD19A66'
    blue:       '0x61AFEF'
    magenta:    '0xC678DD'
    cyan:       '0x56B6C2'
    white:      '0xABB2BF'

  bright:
    black:      '0x5C6370'
    red:        '0xE06C75'
    green:      '0x98C379'
    yellow:     '0xD19A66'
    blue:       '0x61AFEF'
    magenta:    '0xC678DD'
    cyan:       '0x56B6C2'
    white:      '0xFFFFFF'
